### ISSUE TITLE
Wrong calculation when press the enter button

### ISSUE THREAD

**Issue by Achmet97** [Mohammad-Farmaan/JavaScript-Calculator#15]
Hi guys i found a bug in the code. When you input numbers by mouse an click enter from the keyboard it displays wrong calculation.
It displays the calculatoin and paste the last number you cliked with the mouse.

**Comment by Achmet97** [comment]
As you can see on video when you click the numbers by mouse and pres Enter from keyboard is displays wrong result
https://user-images.githubusercontent.com/32641087/154846301-0a4e4772-35d7-4bd2-91a9-e99b7b58cf55.mp4

**Comment by Achmet97** [comment]
As you can see on video when you click the numbers by mouse and pres Enter from keyboard is displays wrong result.

https://user-images.githubusercontent.com/32641087/154846603-62e41431-7028-43f3-8f1c-1e35b530e3b0.mp4

**Comment by rajeevcodes0** [comment]
The happens because of some strange behavior, liveScreen() is called with 1 as argument after we press the Enter key. The calculation works fine though.

**Comment by rajeevcodes0** [comment]
Got it, it is because when you enter inputs using mouse, the last element is still in focus, when when you press "enter", executes the code "enter" key and then the element that was in focus.
1+1 will give 21
1+8 will give 98
A possible solution might be to blur the last key that was entered through mouse to shift the focus to the document.

**Comment by rajeevcodes0** [comment]
Got it, it is because when you enter inputs using mouse, the last element is still in focus, when you press "enter" using the keyboard, the code for 'enter' runs and after that liveScreen() is called for the last element that was in focus.
1+1 will give 21
1+8 will give 98
This is a default behavior of the browser with space and enter key, we can use
` e.preventDefault()`
inside the keyboardInputHandler() to fix this bug.

**Comment by zxcodes** [comment]
It's been fixed by @rajeevcodes0. I've merged it in the master branch.
